application: go-tracer
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  
- url: /fetch
  script: fetch.py

- url: /game\.sgf
  script: makesgf.py

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /css
  static_dir: css
